#version
#services
#volumes

versions: '3.0'

services:
    db:
      image: mysql:8.0
      restart: always #restarts when it shuts off
      environment:
        MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
        MYSQL_DATABASE: ${MYSQL_DATABASE}
        MYSQL_USER: ${MYSQL_USER}
        MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      ports:
        - "3306:3306"
      volumes:
        -./db-data1/var/lib/msql
volumes:
  db-demo-volume:


